# Generated by Django 2.2.6 on 2019-10-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User', to_field='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Активный', max_length=30),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
